### PR TITLE
Add more envs and plugins

### PR DESCRIPTION
**Pull request by dochang**
New envs:
- erlenv
- exenv
- hsenv
- nenv
- nodenv

New plugins:
- plenv
  - plenv-contrib
- pyenv
  - pyenv-alias
  - pyenv-ccache
  - pyenv-doctor
  - pyenv-implict
  - pyenv-installer
  - pyenv-pip-migrate
  - pyenv-pip-rehash
  - pyenv-register
  - pyenv-update
  - pyenv-version-ext
  - pyenv-virtualenv
  - pyenv-virtualenvwrapper
  - pyenv-which-ext
- rbenv
  - rbenv-aliases
  - rbenv-bootstrap
  - rbenv-communal-gems
  - rbenv-ctags
  - rbenv-default-gems
  - rbenv-each
  - rbenv-gem-rehash
  - rbenv-gemset
  - rbenv-installer
  - rbenv-update
  - rbenv-use
  - rbenv-user-gems
  - rbenv-vars
  - rbenv-whatis

### CODE REVIEW

**Comment by riywo** [comment]
This is interesting. I think xx-build plugin should be installed when xxenv is installed, but other plugins should be optional for most people.

How do you feel about introducing a new subcommand for plugin install? Like `anyenv plugin`:

```
$ anyenv plugin plenv plenv-contrib
$ anyenv plugin rbenv rbenv-aliases
```

Finding a good repository of the plugin is painful work for everyone as well as xxenv itself, so plugins catalog like you committed is very effective.

**Comment by dochang** [comment]
A new command is better.  I'd like to run the command like this:

```
$ anyenv plugin rbenv <plugin1> <plugin2> ...
$ anyenv plugin rbenv -a/--all
$ anyenv plugin rbenv -l/--list
```

For this new command, changing definition file format would be better.  i.e., put a plugin definition into its own file.

**Comment by devinus** [comment]
This is very cool. I've been waiting for somebody to add `erlenv`/`exenv` support for some time now!

**Comment by devinus** [comment]
@riywo I've been anxiously waiting for this and https://github.com/riywo/ndenv/pull/4 to land. Is there any way we can get some more collaborators on these projects to speed these up? I really love anyenv and as a polyglot programmer, it has completely replaced my need to individually install all my language envs. If there's any way I can help, let me know.

**Comment by riywo** [comment]
@devinus Hi, thank you for your proposal. I think this PR should be split to adding new env and plugin support. I will accept the former one as soon as possible.

I will add you to the ndenv/node-build collaborator.

**Comment by cdwilson** [comment]
@riywo any update on the 'plugin' subcommand?  in the mean time, what is the recommended way to install plugins for each environment?

**Comment by jalcine** [comment]
@cdwilson So far, it looks like `git clone $REPO_URL $(xenv root)/plugins/$PLUGIN`.

**Comment by minhoryang** [comment]
+1 !!!!! WHAT ARE WE WAITING FOR?

**Comment by riywo** [comment]
Hi all,

I'm considering about splitting anyenv itself and env/plugin list. I'd like to hear your opinions against this idea at https://github.com/riywo/anyenv/issues/46

Best,

**Comment by riywo** [comment]
In the new [anyenv/anyenv](https://github.com/anyenv/anyenv), you can easily write your own manifest.

**Pull request closed without merging**
