### PR TITLE
Change the goenv repository url

### PR DESCRIPTION
**Pull request by segfaults**
Hello there.

I'd prefer the repository of goenv because this is maintained by its owner.

Thanks!

### CODE REVIEW

**Comment by segfaults** [comment]
Additional note;
The previous url is not working correctly due to no maintain. (See https://github.com/dataich/goenv/pull/3)

**Comment by futabooo** [comment]
@riywo Can you please merge this?

**Comment by kaneshin** [comment]
Hi @riywo and @segfaults 

Thank you for your consideration and request.

kaneshin/goenv is fixed some bugs which are contained in wfarr/goenv and dataich/goenv.
And I support to lookup binaries from GOBIN, OSX compatible to download source, Google App Engine installation and a few completions.

I know that there are no maintained goenvs except mine.
So, I highly highly highly recommend to apply the PR.

Thank you.

**Comment by riywo** [comment]
Thanks!

**Pull request merged**
